# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cb809d4c2ce596b7078e7739d503d0f1cd70f47bf6b6bd0cbb7c8ef77612578f2a147d47ba4db11c2c8aa68000fe6ba4c618106a3defbc4b4c7b1262b71f6ca

test:
  secret_key_base: 19c238a0c330d5d0fa885569123819963e4e19860a59ac1d30fd6de120bc568ef6f8d8e0df7182e1672501ec5d9ea2352d230061785838841fc59fd770903ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
